### ISSUE TITLE
Pin

### ISSUE THREAD

**Issue by johnaweiss** [hankxdev/one-click-extensions-manager#128] opened 2024-06-16 15:38 UTC
Hi,

Love this extension. But after i add a new extension, i must click Chrome Extensions button and search the list of extensions to pin the new extension. It an inconvenience because i have a lot of extensions, and it can be hard to find, especially since the Chrome list doesn't have a search feature. 

It would be great if i could pin extensions using One Click Extensions manager. 

Thx!

**Comment by fregante** [comment] 2024-06-16 16:26
Duplicate of https://github.com/hankxdev/one-click-extensions-manager/issues/81

**Closed** 2024-06-16 16:25 UTC
