### ISSUE TITLE
[Feature request] Add favorite/pin extension feature

### ISSUE THREAD

**Issue by inson1** [hankxdev/one-click-extensions-manager#118] opened 2023-10-21 06:31 UTC
I also want #81 
Without that I cant use it. Cant you just set it as option in setting? Please?

**Comment by fregante** [comment] 2023-10-21 07:15
Duplicate of https://github.com/hankxdev/one-click-extensions-manager/issues/81

**Closed by fregante** 2023-10-21 07:15 UTC

**Comment by fregante** [comment] 2023-10-21 08:17
That issue was locked, that means we do not need your "me too" comment. 

> Without that I cant use it.

If you don't want to use this extension, don't use it.
